[limits]

# global affects all quota across the entire instance
"global" = [
		{ seconds = 1, quota = 10 },
		{ minutes = 10, quota = 100 },
		{ days = 1, quota = 500 },
]

"guild/{guild_id}" = [
		{ seconds = 1, quota = 3 },
		{ minutes = 1, quota = 10 },
		{ hours = 1, quota = 30 },
]

"channel/{channel_id}" = [
		{ seconds = 5, quota = 1 },
]

"user/{user_id}" = [
		{ seconds = 15, quota = 2 },
		{ minutes = 1, quota = 10 },
		{ hours = 6, quota = 60 },
]
